name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install --no-cache-dir -U pip .['dev']
      - name: Lint check with flake8
        run: python scripts/ci.py lint
      - name: Format check with black
        run: python scripts/ci.py format
      - name: Type check with mypy
        run: python scripts/ci.py type 
      - name: CVE check with pip-audit
        run: python scripts/ci.py cve
      - name: Security check with bandit
        run: python scripts/ci.py security